# Test your FastAPI endpoints

### Test encoding a URL
POST http://127.0.0.1:8000/encode/
Content-Type: application/json

{
  "original_url": "https://www.markant.com/en/markant-group-contacts-of-the-national-companies/contact-poland"
}

### Test decoding a URL
POST http://127.0.0.1:8000/decode/
Content-Type: application/json

{
  "short_url": "http://short.est/2Qqa35"
}
