"""
Models module for the URL shortening service.
"""

from pydantic import BaseModel


class URLModel(BaseModel):
    """
    Pydantic model representing the original URL.

    Attributes:
        original_url (str): The original URL provided by the user.
    """
    original_url: str


class ShortURLModel(BaseModel):
    """
    Pydantic model representing the shortened URL.

    Attributes:
        short_url (str): The shortened URL generated by the application.
    """
    short_url: str
